version: '3'
services:
  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      MYSQL_ROOT_Host: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - "3035:3035"
  web:
    build:
      context: .
    tty: true
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
